<?php

return [
    [
        'destination' => 'Parigi, Francia',
        'description' => 'Esplora la città dell\'amore con un pacchetto di 5 giorni che include visite guidate e cene gourmet.',
        'price' => 899.99,
        'days' => 5,
        'accommodation' => 'Hotel a 4 stelle',
        'transport' => 'Volo',
        'departure_location' => 'New York, USA',
        'departure_date' => '2024-09-20',
        'return_date' => '2024-09-25',
        'max_participants' => 20,
    ],
    [
        'destination' => 'Tokyo, Giappone',
        'description' => 'Vivi l\'esperienza della fusione tra tradizione e modernità in un viaggio di 7 giorni.',
        'price' => 1299.99,
        'days' => 7,
        'accommodation' => 'Hotel a 5 stelle',
        'transport' => 'Volo',
        'departure_location' => 'Roma, Italia',
        'departure_date' => '2024-10-10',
        'return_date' => '2024-10-17',
        'max_participants' => 15,
    ],
    [
        'destination' => 'Santorini, Grecia',
        'description' => 'Rilassati sulle spiagge bianche di Santorini con un pacchetto di 4 giorni all-inclusive.',
        'price' => 599.99,
        'days' => 4,
        'accommodation' => 'Resort a 5 stelle',
        'transport' => 'Traghetto',
        'departure_location' => 'Atene, Grecia',
        'departure_date' => '2024-08-01',
        'return_date' => '2024-08-05',
        'max_participants' => 10,
    ],
    [
        'destination' => 'Reykjavik, Islanda',
        'description' => 'Scopri i paesaggi mozzafiato dell\'Islanda con un tour di 6 giorni attraverso geyser e vulcani.',
        'price' => 1099.99,
        'days' => 6,
        'accommodation' => 'Hotel a 3 stelle',
        'transport' => 'Volo',
        'departure_location' => 'Londra, Regno Unito',
        'departure_date' => '2024-11-05',
        'return_date' => '2024-11-11',
        'max_participants' => 12,
    ],
    [
        'destination' => 'Cairo, Egitto',
        'description' => 'Esplora le meraviglie antiche dell\'Egitto con un tour di 7 giorni tra le piramidi e il fiume Nilo.',
        'price' => 899.99,
        'days' => 7,
        'accommodation' => 'Hotel a 4 stelle',
        'transport' => 'Volo',
        'departure_location' => 'Milano, Italia',
        'departure_date' => '2024-12-15',
        'return_date' => '2024-12-22',
        'max_participants' => 25,
    ],
];
